### ISSUE TITLE
Shortcut no longer works after PC sleep

### ISSUE THREAD

**Issue by stubbz00** [heftyy/sb-output-controller#2]
First off I would like to say that this controller is awesome and I've been looking for something to do exactly what this does for quite awhile.  So thank you.

As far as the issue, it seems that after I wake my computer the shortcut no longer works, so I have to close the controller and re-open it.  I'm not sure if it's because the G6 is not initially recognized after the PC wakes.  Have you come across this issue, or might know a way to resolve this?

**Comment by heftyy** [comment]
I can confirm that I get the same issue, not sure when I will have the time or will to look into though. I seem to remember some ways in windows to listen to the wake up events so there is hope!

**Comment by stubbz00** [comment]
I'm glad you can confirm this.  I've also noticed that if you click register without closing the controller it will start working again as well.  Not sure if that is something to look into as well.

**Comment by heftyy** [comment]
Should be fixed in v1.0.5. It seems like my G6 needed a bit of time after windows resumes so I set an arbitrary delay of 5s before I reinitialize the driver. Maybe I will need to add something that retries multiple times but I think it should be fine as is. 
Let me know if the new release works for you.

**Comment by stubbz00** [comment]
Yes!  From a couple of tests I performed this update resolved the issue.  Thank you for working on this.  It's working perfectly now!
