### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by Hamburgalarr** [heftyy/sb-output-controller#3]
Love the program thanks! Any chance of being able to switch speakers/headphone and switch direct mode off/on same time?>

**Comment by heftyy** [comment]
Added direct mode checkboxes that will apply when the output mode is switched. 
![image](https://user-images.githubusercontent.com/6159098/124034206-368a8b00-d9fb-11eb-8d94-b9dfb32f6b9c.png)

released in v1.1.0
